import { ITableViewField } from "@/src/components/TableView"
import { JALALI_MONTHS } from "@/src/constants"
import { IRecordPopulated } from "@/src/lib/module/common/types"

export const filters = {
    user: 'براساس کاربر',
    title: 'براساس عنوان',
}

export const recordSchemaFields: ITableViewField<IRecordPopulated>[] = [
    { 
        key: 'hospital',
        type: 'none',
        title: 'بیمارستان',
        alt: '', 
        viewCol: true 
    },
    { 
        key: 'year',
        type: 'number',
        title: 'سال',
        alt: '', 
        viewCol: true, 
    },
    { 
        key: 'month',
        type: 'select',
        title: 'ماه',
        alt: '', 
        options: JALALI_MONTHS.map((m, i) => ({value: i.toString(), label: m})),
        viewCol: true,
    },
    { 
        key: 'rIn',
        type: 'number',
        title: 'درآمد بستری',
        alt: '', 
        viewCol: false,
    },
    { 
        key: 'rOut',
        type: 'number',
        title: 'درآمد سرپایی',
        alt: '', 
        viewCol: false,
    },
    { 
        key: 'vTotal',
        type: 'number',
        title: 'تعداد کل ویزیت‌ها',
        alt: '', 
        viewCol: false,
    },
    { 
        key: 'sTotal',
        type: 'number',
        title: 'تعداد کل جراحی‌ها',
        alt: '', 
        viewCol: false,
    },
    { 
        key: 'dTotal',
        type: 'number',
        title: 'تعداد ترخیص بیمار',
        alt: '', 
        viewCol: false,
    },
    { 
        key: 'beds',
        type: 'number',
        title: 'تعداد تخت فعال',
        alt: '', 
        viewCol: false,
    },
    { 
        key: 'oDays',
        type: 'number',
        title: 'تخت‌روز اشغال شده',
        alt: '', 
        viewCol: false,
    },
    { 
        key: 'sDays',
        type: 'number',
        title: 'مجموع روزهای بستری',
        alt: '', 
        viewCol: false,
    },
    { 
        key: 'mDays',
        type: 'number',
        title: 'تعداد روزهای ماه',
        alt: '', 
        viewCol: false,
    },
    { 
        key: 'ins1',
        type: 'number',
        title: 'مطالبات ارسالی - تأمین اجتماعی',
        alt: '', 
        viewCol: false,
    },
    { 
        key: 'ins2',
        type: 'number',
        title: 'مطالبات ارسالی - بیمه سلامت',
        alt: '', 
        viewCol: false,
    },
    { 
        key: 'ins3',
        type: 'number',
        title: 'مطالبات ارسالی - سایر',
        alt: '', 
        viewCol: false,
    },
    { 
        key: 'received',
        type: 'number',
        title: 'مبلغ وصول شده (نقد)',
        alt: '', 
        viewCol: false,
    },
    { 
        key: 'ded',
        type: 'number',
        title: 'مبلغ کسورات قطعی',
        alt: '', 
        viewCol: false,
    },
    { 
        key: 'totalRev',
        type: 'none',
        title: 'درآمد کل',
        alt: '', 
        viewCol: true,
    },
    { 
        key: 'rDoc',
        type: 'none',
        title: 'جز حرفه‌ای',
        alt: '', 
        viewCol: true,
    },
    { 
        key: 'bor',
        type: 'none',
        title: '%BOR',
        alt: '', 
        viewCol: true,
    },
    { 
        key: 'alos',
        type: 'none',
        title: 'ALOS',
        alt: '', 
        viewCol: true,
    },
    { 
        key: 'revCase',
        type: 'none',
        title: 'درآمد/بیمار (م.ر)',
        alt: '', 
        viewCol: true,
    },
    { 
        key: 'dedPerc',
        type: 'none',
        title: 'کسورات٪',
        alt: '', 
        viewCol: true,
    },
    { 
        key: 'collRatio',
        type: 'none',
        title: 'وصول٪',
        alt: '', 
        viewCol: true,
    },
    { 
        key: 'location',
        type: 'none',
        title: 'مرکز',
        alt: '', 
        viewCol: false,
    },
]
